app1:
  image: tomcat
  volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml:ro
app2:
  image: tomcat
  volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml:ro
app3:
  image: tomcat
  volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml:ro
nginx:
  image: nginx:alpine
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  links:
    - app1
    - app2
    - app3
  ports:
    - "90:90"