# Docker Compose YAML file for lighttpd

# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

# after start, enter shell with:
# $ sudo docker exec -it lighttpddocker_lighttpd_1 ash

lighttpd:
    container_name: lighttpd
    build: .
    restart: always
    #ports:
    #    - "8001:80" # for testing purposes, (un)comment as required
    tty: 
        true
    volumes:
        - ./htdocs/index.html:/var/www/localhost/htdocs/index.html:ro


lighttpd1:
    container_name: lighttpd1
    build: .
    restart: always
    #ports:
    #    - "8001:80" # for testing purposes, (un)comment as required
    tty: 
        true
    volumes:
        - ./htdocs/index.html:/var/www/localhost/htdocs/index.html:ro

lighttpd2:
    container_name: lighttpd2
    build: .
    restart: always
    #ports:
    #    - "8001:80" # for testing purposes, (un)comment as required
    tty: 
        true
    volumes:
        - ./htdocs/index.html:/var/www/localhost/htdocs/index.html:ro

nginx:
  image: nginx:alpine
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  links:
    - lighttpd
    - lighttpd1
    - lighttpd2
  ports:
    - "90:90"