# Docker Compose YAML file for lighttpd

# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

# after start, enter shell with:
# $ sudo docker exec -it lighttpddocker_lighttpd_1 ash

lighttpd:
    container_name: lighttpd
    build: .
    restart: always
    ports:
        - "8001:80" # for testing purposes, (un)comment as required
    tty: 
        true
    volumes:
        - ./htdocs/index.html:/var/www/localhost/htdocs/index.html:ro
